[package]
name = "segment-tree-by-min"
version = "0.1.0"
edition = "2021"

[dependencies]
max-exists = { path = "../max-exists.lib" }
min-monoid = { path = "../min-monoid.lib" }
segment-tree = { path = "../segment-tree.lib" }
