[package]
name = "segment-tree-by-max"
version = "0.1.0"
edition = "2021"

[dependencies]
max-monoid = { path = "../max-monoid.lib" }
min-exists = { path = "../min-exists.lib" }
segment-tree = { path = "../segment-tree.lib" }
