[package]
name = "segment-tree-by-max"
version = "0.1.0"
edition = "2021"

[dependencies]
max-monoid = { path = "../algebraic-structures.col/monoid.col/max-monoid.lib" }
min-exists = { path = "../algebraic-structures.col/ord.col/min-exists.lib" }
segment-tree = { path = "../segment-tree.lib" }
