[package]
name = "accum"
version = "0.1.0"
edition = "2021"

[dependencies]
access-range = { path = "../access-range.lib" }
com-ring = { path = "../algebraic-structures.col/com-ring/core.lib" }
group = { path = "../algebraic-structures.col/group/core.lib" }
