[package]
name = "segment-tree-by-add"
version = "0.1.0"
edition = "2021"

[dependencies]
add-monoid = { path = "../add-monoid.lib" }
commutative-ring = { path = "../commutative-ring.lib" }
segment-tree = { path = "../segment-tree.lib" }
