[package]
name = "group-as-monoid"
version = "0.1.0"
edition = "2021"

[dependencies]
group = { path = "../core.lib" }
monoid = { path = "../../monoid.col/monoid.lib" }
transparent-derive = { path = "../../../transparent/derive.lib" }
transparent-trait = { path = "../../../transparent/trait.lib" }
