[package]
name = "int"
version = "0.1.0"
edition = "2021"

[dependencies]
com-ring = { path = "../com-ring/core.lib" }
com-ring-ord = { path = "../com-ring-ord.lib" }
max-exists = { path = "../ord.col/max-exists.lib" }
min-exists = { path = "../ord.col/min-exists.lib" }
