[package]
name = "max-monoid"
version = "0.1.0"
edition = "2021"

[dependencies]
transparent-trait = { path = "../transparent-trait.lib" }
transparent-derive = { path = "../transparent-derive.lib" }
min-exists = { path = "../min-exists.lib" }
monoid = { path = "../monoid.lib" }
