[package]
name = "add-monoid"
version = "0.1.0"
edition = "2021"

[dependencies]
monoid = { path = "../monoid.lib" }
commutative-ring = { path = "../commutative-ring.lib" }
transparent-trait = { path = "../transparent-trait.lib" }
transparent-derive = { path = "../transparent-derive.lib" }
