[package]
name = "lazy-segment-tree-util-new-with-size"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy-segment-tree = { path = "../../core.lib" }
lazy-segment-tree-util-type = { path = "../type.lib" }
monoid-action = { path = "../../../algebraic-structures.col/monoid.col/monoid-action.lib" }
shrink-provider = { path = "../../../shrink/provider.lib" }
with-size = { path = "../../../with-size.lib" }
