[package]
name = "lazy-segment-tree-util-new-with-len"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy-segment-tree = { path = "../../core.lib" }
lazy-segment-tree-util-type = { path = "../type.lib" }
shrink-provider = { path = "../../../shrink/provider.lib" }
